var facts = [
	"A large majority of homeless people spend most of their time outdoors",
	"Fish have a low chance of drowning",
	"Most people live till the end of their lifetime",
	"An hour, on average, is around 60 minutes",
	"Software is created using software",
	"WiFi is Wireless!",
	"Most countries have one or more states",
	"Texts often contain letters and words",
	"Cars can only be used when they are fueled",
	"The average person is less than a year old when they are born",
	"Humans are often warmed blooded",
	"Sea mammals often live in water",
	"Most images are composed of colors and shades",
	"Most Englishmen speak English",
	"Fire is commonly hot",
	"Dry ice is ice, most of the time",
	"Water contains around one ingredient",
	"This webpage might be displaying on your monitor right now",
	"Showerheads are usually apart of showers",
	"People most commonly die the day of their death", 
    "Landscapes are usually made up of land",
    "You often use your ears to listen to noises",
    "Bald people often have no hair",
    "If your legs are broken, you're less likely to walk",
    "Trees will most likely need water in order to grow",
	"Scientific research has concluded that closing your eyes could give you temporary vision loss",
	"You often fall while airborne"
];